### ISSUE TITLE
Toggle doesn't show in IE 11

### ISSUE THREAD

**Issue by rupeshambati** [PredixDev/px-toggle-design#2]
Works fine on chrome but doesn't show in IE 11.

![image](https://cloud.githubusercontent.com/assets/23106757/20732259/b76a2dd4-b642-11e6-94b7-750583115b87.png)

![image](https://cloud.githubusercontent.com/assets/23106757/20732290/e8ca918e-b642-11e6-9c3e-327a859cef48.png)

**Comment by mdwragg** [comment]
Fix coming very soon - we're on it.

**Comment by randyaskin** [comment]
Please update to v0.2.23 of px-toggles-design, which reverted the addition of style variables and restored compatibility with IE11/Edge.

**Comment by rupeshambati** [comment]
Awesome. Thanks.
