### ISSUE TITLE
Cant use polymer element multiple times which has toggle 

### ISSUE THREAD

**Issue by LRagji** [PredixDev/px-toggle-design#3]
Hi i am trying to create a custom polymer 1.0 element like shown below:
`<dom-module id="rm-gt-card">
    <template>
<input id="example" type="checkbox" class="toggle__input">
<label for="example" class="toggle__label"></label>
</template>`
The above element when placed on page works like a charm, but the problem starts when i use the element more than once on the page only one of the element works 
Googling got me this far which states id's cannot be used inside a polymer element is there any alternative suggested for the same?

**Comment by nonmetalhail** [comment]
This does not appear to be an issue related to the toggle design repo. Please do not open random, unrelated issues. To learn how to use polymer, check out https://www.polymer-project.org/

**Comment by LRagji** [comment]
@nonmetalhail I think you should really investigate before calling it not a bug: if you can check this repo https://github.com/LRagji/pagina its a fork of Predix seed application it has element "rm-gt-card" this is using toggle design which is then bound to the app page called peak power when the design style is used check box style is broken when its not the functionality works

**Comment by nonmetalhail** [comment]
I'm reading your first post as you wanting help on how to build a Polymer element. I do not see anything specifically pertaining to this repo. If you feel this is an issue directly relating to this repo, please explain exactly the issue you are experiencing and post a working codepen demonstrating the issue

**Comment by LRagji** [comment]
Ok let me put this in a better way: below is a polymer component that i am creating using toggle-design:`<dom-module id="rm-gt-card"><template><input id="someId" checked={{shortView::change}} class="toggle__input" type="checkbox"><label for="someId" class="toggle__label"></label></template><script>Polymer({is: 'rm-gt-card',properties: {}})</script></dom-module>`
**Problem**: if i add multiple of this element 'rm-gt-card' on my html page they do not toggle except the first one

I hope i am clear this time

**Comment by mdwragg** [comment]
Hi, maybe we can cut to the chase a little, can you show us a codepen exhibiting the error you are raising? If we can see the issue and recreate it, we stand a much better chance of fixing it.

Thanks,
Martin.

**Comment by mdwragg** [comment]
Hi,

You've got two choices I think. Either enforce Shadow DOM in your browser (assuming you're using a browser capable of shadow dom). This will correctly 'protect' reuse of IDs in the shadow 'sub tree'.

Or create some form of unique ID for your toggle element in your web component. A little like the implementation here:

https://github.com/mdwragg/px-toggle-test/blob/master/px-toggle-test.html

This should be a complete example in that repo:

`git clone https://github.com/mdwragg/px-toggle-test/`
`cd px-toggle-test`
`yarn install`
`bower install`
`gulp serve`

and browse to http://localhost:8080/demo.html to see it in action.

This issue would go away anyway with the advent of Polymer 2.0 - shady dom (the approximation of shadow dom disappears and is replaced either by native support by the browser or the full web component polyfills. For now the two options above should serve you well.

M.

**Comment by LRagji** [comment]
Thanks @mdwragg i think i will stick with random ids approach until Polymer 2.0, if you can also consider achieving the same design behaviour using iron-label it should remove the dependency of id and for attribute from the html label..?

I initially thought this is a bug of toggle-design so wrote it in the bug section, now i think this is more of how the polymer framework behaves; not sure if this is required but you can also warn folks about using toggle-design inside a element which can be repeated multiple times on their page.(maybe noob mistake) :)

**Comment by mdwragg** [comment]
👍 Thanks @LRagji. We have on our backlog to create a toggle web component that will wrap this sass partial.

I'm glad the example works for you though.
